package config

import "time"

func Default() Config {
	return Config{
		Version: CurrentConfigVersion,
		Node: NodeConfig{
			Environment: "production",
			Ring:        "alpha",
		},
		API: APIConfig{
			Enabled: true,
			Bind:    DefaultAPIBind,
		},
		Logging: LoggingConfig{
			Level:  "info",
			Format: "text",
		},
		Commands: CommandPaths{
			Systemctl:  "/bin/systemctl",
			Journalctl: "/bin/journalctl",
			SSHD:       "/usr/sbin/sshd",
			SS:         "/usr/sbin/ss",
			UFW:        "/usr/sbin/ufw",
			Visudo:     "/usr/sbin/visudo",
			Auditctl:   "/usr/sbin/auditctl",
			Ausearch:   "/usr/sbin/ausearch",
		},
		Resources: ResourcesConfig{
			Enabled:  true,
			Interval: Duration{Duration: 30 * time.Second},
			Timeout:  Duration{Duration: 3 * time.Second},
			CPU:      ResourceToggleConfig{Enabled: true},
			Memory:   ResourceToggleConfig{Enabled: true},
			Pressure: PressureConfig{Enabled: true, MissingIsOK: true},
			Filesystem: FilesystemConfig{
				Enabled: true,
				Mounts:  []string{"/", "/home", "/var", "/var/log", "/var/lib", "/var/lib/pooly-sentinel", "/var/log/pooly-sentinel"},
			},
			DiskIO: DiskIOConfig{
				Enabled:      true,
				AutoDiscover: true,
				Exclude:      []string{"loop*", "ram*", "fd*", "sr*"},
			},
			Network: NetworkConfig{
				Enabled:      true,
				AutoDiscover: true,
				Include:      []string{},
				Exclude:      []string{"lo", "docker*", "veth*", "br-*"},
			},
			Uptime: ResourceToggleConfig{Enabled: true},
		},
		Systemd: SystemdConfig{
			Enabled:  false,
			Interval: Duration{Duration: 30 * time.Second},
			Timeout:  Duration{Duration: 3 * time.Second},
			CriticalServices: []string{
				"ssh.service",
				"fail2ban.service",
				"pooly-sentinel-agent.service",
				"miningcore.service",
			},
		},
		SSH: SSHConfig{
			Enabled:     false,
			Interval:    Duration{Duration: 5 * time.Minute},
			Timeout:     Duration{Duration: 3 * time.Second},
			EventDriven: true,
			Expected: SSHExpectedConfig{
				Ports:                        []int{6200},
				ForbiddenPorts:               []int{22},
				PermitRootLogin:              "no",
				PasswordAuthentication:       "no",
				KbdInteractiveAuthentication: "no",
				PermitEmptyPasswords:         "no",
				PubkeyAuthentication:         "yes",
				StrictModes:                  "yes",
				PermitUserEnvironment:        "no",
			},
		},
		Journal: JournalConfig{
			Auth: JournalStreamConfig{
				Enabled:       false,
				Interval:      Duration{Duration: 10 * time.Second},
				Timeout:       Duration{Duration: 3 * time.Second},
				MaxRecords:    100,
				MaxBytes:      256 * 1024,
				MaxFieldBytes: 512,
			},
			Services: JournalStreamConfig{
				Enabled:       false,
				Interval:      Duration{Duration: 30 * time.Second},
				Timeout:       Duration{Duration: 3 * time.Second},
				MaxRecords:    100,
				MaxBytes:      256 * 1024,
				MaxFieldBytes: 512,
			},
			Kernel: JournalStreamConfig{
				Enabled:       false,
				Interval:      Duration{Duration: 60 * time.Second},
				Timeout:       Duration{Duration: 3 * time.Second},
				MaxRecords:    100,
				MaxBytes:      256 * 1024,
				MaxFieldBytes: 512,
			},
		},
		Filewatch: FilewatchConfig{
			Enabled:                false,
			Debounce:               Duration{Duration: 2 * time.Second},
			PeriodicVerifyInterval: Duration{Duration: 5 * time.Minute},
			Timeout:                Duration{Duration: 3 * time.Second},
			MaxFileBytes:           1024 * 1024,
			MaxDirectoryEntries:    256,
			Targets:                []FilewatchTargetConfig{},
		},
		Audit: AuditConfig{
			Enabled:     false,
			Mode:        "observe_only",
			ManageRules: false,
		},
		Rules: defaultRules(),
		Notification: NotificationConfig{
			PaidReceiversEnabledByDefault: false,
		},
		Receivers: []ReceiverConfig{
			{
				Name:      "local_file",
				Type:      "file",
				CostClass: "free_core",
				Enabled:   true,
			},
		},
		Storage: StorageConfig{
			StateDir:           DefaultStateDir,
			LogDir:             DefaultLogDir,
			DatabaseFile:       "state.db",
			CurrentMetricsFile: "metrics-current.json",
			SQLite: SQLiteConfig{
				BusyTimeout: Duration{Duration: 5 * time.Second},
				WAL:         true,
			},
		},
	}
}

func defaultRules() []RuleConfig {
	return []RuleConfig{
		{
			ID:          "cpu-used-sustained",
			Enabled:     true,
			Collector:   "resources",
			Metric:      "pooly_cpu_used_ratio",
			Target:      "system",
			Warn:        &RuleThresholdConfig{Operator: "greater_than_or_equal", Value: 0.85, For: Duration{Duration: 10 * time.Minute}},
			Fail:        &RuleThresholdConfig{Operator: "greater_than_or_equal", Value: 0.95, For: Duration{Duration: 10 * time.Minute}},
			RecoverFor:  Duration{Duration: 5 * time.Minute},
			MissingData: "stale",
			StaleData:   "stale",
			Summary:     "{{rule_id}} threshold state for {{target}}",
		},
		{
			ID:          "memory-available-low",
			Enabled:     true,
			Collector:   "resources",
			Metric:      "pooly_memory_available_ratio",
			Target:      "system",
			Warn:        &RuleThresholdConfig{Operator: "less_than", Value: 0.15, For: Duration{Duration: 10 * time.Minute}},
			Fail:        &RuleThresholdConfig{Operator: "less_than", Value: 0.08, For: Duration{Duration: 10 * time.Minute}},
			Critical:    &RuleThresholdConfig{Operator: "less_than", Value: 0.04, For: Duration{Duration: 5 * time.Minute}},
			RecoverFor:  Duration{Duration: 5 * time.Minute},
			MissingData: "stale",
			StaleData:   "stale",
			Summary:     "{{rule_id}} threshold state for {{target}}",
		},
		{
			ID:          "filesystem-capacity-high",
			Enabled:     true,
			Collector:   "filesystem",
			Metric:      "pooly_filesystem_used_ratio",
			Target:      "any",
			Warn:        &RuleThresholdConfig{Operator: "greater_than_or_equal", Value: 0.85, For: Duration{Duration: 10 * time.Minute}},
			Fail:        &RuleThresholdConfig{Operator: "greater_than_or_equal", Value: 0.95, For: Duration{Duration: 10 * time.Minute}},
			RecoverFor:  Duration{Duration: 5 * time.Minute},
			MissingData: "stale",
			StaleData:   "stale",
			Summary:     "{{rule_id}} threshold state for {{target}}",
		},
		{
			ID:          "filesystem-inodes-high",
			Enabled:     true,
			Collector:   "filesystem",
			Metric:      "pooly_filesystem_inodes_used_ratio",
			Target:      "any",
			Warn:        &RuleThresholdConfig{Operator: "greater_than_or_equal", Value: 0.85, For: Duration{Duration: 10 * time.Minute}},
			Fail:        &RuleThresholdConfig{Operator: "greater_than_or_equal", Value: 0.95, For: Duration{Duration: 10 * time.Minute}},
			RecoverFor:  Duration{Duration: 5 * time.Minute},
			MissingData: "stale",
			StaleData:   "stale",
			Summary:     "{{rule_id}} threshold state for {{target}}",
		},
		{
			ID:          "required-network-interface-down",
			Enabled:     false,
			Collector:   "network",
			Metric:      "pooly_network_interface_up",
			Target:      "eth0",
			Fail:        &RuleThresholdConfig{Operator: "boolean_false", For: Duration{Duration: 2 * time.Minute}},
			RecoverFor:  Duration{Duration: 2 * time.Minute},
			MissingData: "stale",
			StaleData:   "stale",
			Summary:     "{{rule_id}} threshold state for {{target}}",
		},
		{
			ID:          "required-systemd-service-failed",
			Enabled:     false,
			Collector:   "systemd",
			Metric:      "pooly_systemd_unit_failed",
			Target:      "ssh.service",
			Fail:        &RuleThresholdConfig{Operator: "boolean_true", For: Duration{Duration: 1 * time.Minute}},
			RecoverFor:  Duration{Duration: 2 * time.Minute},
			MissingData: "stale",
			StaleData:   "stale",
			Summary:     "{{rule_id}} threshold state for {{target}}",
		},
		{
			ID:          "forbidden-ssh-listener",
			Enabled:     false,
			Collector:   "ssh_listeners",
			Metric:      "pooly_ssh_forbidden_port_listening",
			Target:      "22",
			Fail:        &RuleThresholdConfig{Operator: "boolean_true", For: Duration{Duration: 1 * time.Minute}},
			RecoverFor:  Duration{Duration: 2 * time.Minute},
			MissingData: "stale",
			StaleData:   "stale",
			Summary:     "{{rule_id}} threshold state for {{target}}",
		},
		{
			ID:          "ssh-hardening-drift",
			Enabled:     false,
			Collector:   "ssh_effective_config",
			Metric:      "pooly_ssh_directive_expected_match",
			Target:      "any",
			Warn:        &RuleThresholdConfig{Operator: "boolean_false", For: Duration{Duration: 5 * time.Minute}},
			Fail:        &RuleThresholdConfig{Operator: "boolean_false", For: Duration{Duration: 30 * time.Minute}},
			RecoverFor:  Duration{Duration: 5 * time.Minute},
			MissingData: "stale",
			StaleData:   "stale",
			Summary:     "{{rule_id}} threshold state for {{target}}",
		},
		{
			ID:            "kernel-oom-event",
			Enabled:       false,
			Collector:     "journal",
			EventCategory: "kernel_oom",
			Target:        "kernel",
			Fail:          &RuleThresholdConfig{Operator: "event_category_match", Value: "kernel_oom", For: Duration{Duration: 0}},
			RecoverFor:    Duration{Duration: 5 * time.Minute},
			MissingData:   "stale",
			StaleData:     "stale",
			Summary:       "{{rule_id}} event state for {{target}}",
		},
	}
}
